version: '3'
services:
  prometheus:
    image: docker.artifactory.tapsi.tech/prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

